kafka.bootstrap.servers=${KAFKA_BOOTSTRAP_SERVER:localhost:9092}

mp.messaging.incoming.source.connector=smallrye-kafka
#mp.messaging.incoming.source.sasl.mechanism=SCRAM-SHA-512
#mp.messaging.incoming.source.security.protocol=SASL_PLAINTEXT
#mp.messaging.incoming.source.sasl.jaas.config=org.apache.kafka.common.security.scram.ScramLoginModule required username="${KAFKA_USER:admin}" password="${KAFKA_PWD:admin-secret}";
mp.messaging.incoming.source.topic=test-in
mp.messaging.incoming.source.group.id=${CONSUMER_GROUP:demo-group}
mp.messaging.incoming.source.value.deserializer=org.apache.kafka.common.serialization.ByteArrayDeserializer

mp.messaging.outgoing.target.connector=smallrye-kafka
#mp.messaging.outgoing.target.sasl.mechanism=SCRAM-SHA-512
#mp.messaging.outgoing.target.security.protocol=SASL_PLAINTEXT
#mp.messaging.outgoing.target.sasl.jaas.config=org.apache.kafka.common.security.scram.ScramLoginModule required username="${KAFKA_USER:admin}" password="${KAFKA_PWD:admin-secret}";
mp.messaging.outgoing.target.topic=test-out
mp.messaging.outgoing.target.value.serializer=org.apache.kafka.common.serialization.StringSerializer


